"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/lib/provider/AppProvider/AppProvider";
import SideBar from "@/ui/Button/NavBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar /> {/* Esto no iria aca */}
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
