import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/lib/providers/ThemeProvider";
import { ModeToggle } from "@/ui/dark-theme-toggle/dark-theme-toggle";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={karla.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ModeToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
